#!/bin/bash

# Download the nessesary files
git clone git@github.com:arvintashakori/HyperTransformersPFL.git
cd HyperTransformersPFL/data
!wget --no-check-certificate 'https://drive.google.com/file/d/1QaaMJlTJBHu2gzRRwHoqQ9E7nM6PNMke/view?usp=share_link' -O 'cifar10.npy'
cd
cd HyperTransformersPFL
pip install -e .
python train_FedAVG.py --FL_platform ViT-FedAVG --net_name ViT-small --dataset cifar10 --E_epoch 1 --max_communication_rounds 100 --num_local_clients -1 --split_type split_2 --save_model_flag