#!/bin/bash

# Download biometric
git clone git@github.com:arvintashakori/fdr.git

# Download DHP
git clone git@github.com:arvintashakori/dhp.git

# Download the HyperTransformersPFL files
git clone git@github.com:arvintashakori/HyperTransformersPFL.git

# Download Actionnet
git clone git@github.com:delpreto/ActionNet.git

cd HyperTransformersPFL/data
# wget --no-check-certificate 'https://drive.google.com/uc?export=download&id=18GgUTJTp2WDHz9x6ppfbh064hcXMr8TE' -O cifar10.npy
pip install gdown
gdown 18GgUTJTp2WDHz9x6ppfbh064hcXMr8TE
cd
cd HyperTransformersPFL
pip install -e .
python train_FedAVG.py --FL_platform ViT-FedAVG --net_name ViT-small --dataset cifar10 --E_epoch 1 --max_communication_rounds 100 --num_local_clients -1 --split_type split_2 --save_model_flag
